In [1]:
import pandas as pd
from pathlib import Path

In [5]:
# Caminho base dos dados
DATA = Path("../data")

# Função para carregar todos os CSVs de um prefixo
def load_csvs(prefix):
    files = sorted(DATA.glob(f"{prefix}-*.csv"))
    frames = []
    for file in files:
        df = pd.read_csv(file, sep=";", quotechar='"', low_memory=False)
        df["ano"] = int(file.stem.split("-")[-1])  # salva o ano como coluna
        frames.append(df)
    return pd.concat(frames, ignore_index=True)

In [6]:
votos = load_csvs("voting/votes/votacoesVotos")

votos

,idVotacao,uriVotacao,dataHoraVoto,voto,deputado_id,deputado_uri,deputado_nome,deputado_siglaPartido,deputado_uriPartido,deputado_siglaUf,deputado_idLegislatura,deputado_urlFoto,ano
0,37897-3,https://dadosabertos.camara.leg.br/api/v2/vota...,2001-12-11T19:49:15,Sim,73886.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Adão Pretto,PT,https://dadosabertos.camara.leg.br/api/v2/part...,RS,51,https://www.camara.leg.br/internet/deputado/ba...,2001
1,37897-3,https://dadosabertos.camara.leg.br/api/v2/vota...,2001-12-11T19:29:35,Sim,74328.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Adauto Pereira,PFL,https://dadosabertos.camara.leg.br/api/v2/part...,PB,51,https://www.camara.leg.br/internet/deputado/ba...,2001
2,37897-3,https://dadosabertos.camara.leg.br/api/v2/vota...,2001-12-11T19:26:34,Sim,74450.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Adolfo Marinho,PSDB,https://dadosabertos.camara.leg.br/api/v2/part...,CE,51,https://www.camara.leg.br/internet/deputado/ba...,2001
3,37897-3,https://dadosabertos.camara.leg.br/api/v2/vota...,2001-12-11T19:25:14,Artigo 17,74646.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Aécio Neves,PSDB,https://dadosabertos.camara.leg.br/api/v2/part...,MG,51,https://www.camara.leg.br/internet/deputado/ba...,2001
4,37897-3,https://dadosabertos.camara.leg.br/api/v2/vota...,2001-12-11T19:26:59,Sim,73765.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Affonso Camargo,PFL,https://dadosabertos.camara.leg.br/api/v2/part...,PR,51,https://www.camara.leg.br/internet/deputado/ba...,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1698924,945492-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2024-12-11T13:16:40,Sim,178946.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Soraya Santos,PL,https://dadosabertos.camara.leg.br/api/v2/part...,RJ,57,https://www.camara.leg.br/internet/deputado/ba...,2024
1698925,945492-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2024-12-11T13:16:40,Sim,178934.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Toninho Wandscheer,PP,https://dadosabertos.camara.leg.br/api/v2/part...,PR,57,https://www.camara.leg.br/internet/deputado/ba...,2024
1698926,945492-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2024-12-11T13:16:40,Sim,91228.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Waldemar Oliveira,AVANTE,https://dadosabertos.camara.leg.br/api/v2/part...,PE,57,https://www.camara.leg.br/internet/deputado/ba...,2024
1698927,945492-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2024-12-11T13:16:40,Sim,224333.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Welter,PT,https://dadosabertos.camara.leg.br/api/v2/part...,PR,57,https://www.camara.leg.br/internet/deputado/ba...,2024
1698928,945492-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2024-12-11T13:16:40,Sim,220536.0,https://dadosabertos.camara.leg.br/api/v2/depu...,Zé Haroldo Cathedral,PSD,https://dadosabertos.camara.leg.br/api/v2/part...,RR,57,https://www.camara.leg.br/internet/deputado/ba...,2024

In [7]:
# Exemplo: dropando as colunas 'deputado_uri', 'deputado_uriPartido' e 'deputado_urlFoto'
colunas_para_dropar = ['uriVotacao', 'deputado_uri', 'deputado_nome', 'deputado_uriPartido', 'deputado_urlFoto']
votos = votos.drop(columns=colunas_para_dropar)
votos

,idVotacao,dataHoraVoto,voto,deputado_id,deputado_siglaPartido,deputado_siglaUf,deputado_idLegislatura,ano
0,37897-3,2001-12-11T19:49:15,Sim,73886.0,PT,RS,51,2001
1,37897-3,2001-12-11T19:29:35,Sim,74328.0,PFL,PB,51,2001
2,37897-3,2001-12-11T19:26:34,Sim,74450.0,PSDB,CE,51,2001
3,37897-3,2001-12-11T19:25:14,Artigo 17,74646.0,PSDB,MG,51,2001
4,37897-3,2001-12-11T19:26:59,Sim,73765.0,PFL,PR,51,2001
...,...,...,...,...,...,...,...,...
1698924,945492-151,2024-12-11T13:16:40,Sim,178946.0,PL,RJ,57,2024
1698925,945492-151,2024-12-11T13:16:40,Sim,178934.0,PP,PR,57,2024
1698926,945492-151,2024-12-11T13:16:40,Sim,91228.0,AVANTE,PE,57,2024
1698927,945492-151,2024-12-11T13:16:40,Sim,224333.0,PT,PR,57,2024
1698928,945492-151,2024-12-11T13:16:40,Sim,220536.0,PSD,RR,57,2024

In [8]:
votos.to_csv("votos_agg.csv", index=False, sep=";")